#!/bin/sh

xrandr --newmode  "1360x768_60.00"   84.75  1360 1432 1568 1776  768 771 781 798 -hsync +vsync
xrandr --addmode eDP-0 "1360x768_60.00"
xrandr --output DisplayPort-1 --off --output DisplayPort-0 --off --output HDMI-0 --off --output HDMI-1 --off --output eDP-0 --mode 1360x768_60.00 --pos 0x0 --rotate normal

